[package]
name = "gregory"
version = "0.1.0"
edition = "2021"

[dependencies]
alphanumeric-sort = "1.5.3"
clap = { version = "4.5.23", features = ["derive"] }
clap_complete = "4.5.40"
yaml-rust2 = "0.9.0"

[profile.release]
opt-level = 3
