max-jobs = 4
max-threads = 10

[packages]

  [packages.librewolf]

  dependencies = ["some-librewolf-dependency"]
  version_check = ["check-version --whenever-you-feel-like-it-please"]

    [packages.librewolf.compilation]
    revision = "2"
    threads = 6
    image = "docker.io/library/debian"
    commands = ["echo hi", "echo helloooooooooo"]
    volumes = ["librewolf"]

    [packages.librewolf.packaging.fedora]
    threads = 2
    image = "docker.io/library/fedora"
    commands = [
      "echo did you ever hear the tragedy of darth plageuis the wise?",
      "echo it\\'s not a story the jedi would tell you",
    ]
    volumes = ["librewolf", "fedora-repo"]

  [packages.some-librewolf-dependency]

    [packages.some-librewolf-dependency.compilation]
    revision = "4"
    threads = 2
    image = "docker.io/library/debian"
    commands = ["echo hi", "echo helloooooooooo >&2"]
    volumes = ["other-workspace"]

    [packages.some-librewolf-dependency.packaging.fedora]
    revision = "2"
    threads = 2
    image = "docker.io/library/fedora"
    commands = ["echo hello worldddddddd"]
    volumes = ["other-workspace", "fedora-repo"]

[update-repo]

  [update-repo.fedora]
  threads = 4
  image = 'docker.io/library/fedora'
  commands = ["echo hai"]
  volumes = ["librewolf"]

[volumes]
librewolf = "./data/librewolf:/librewolf"
other-workspace = "./data/other-workspace:/workspace"
fedora-repo = "./data/fedora-repo:/fedora-repo"
